{
 "title": "ElasticSearch",
 "description": "ElasticSearch cluster stats",
 "tags": [
  "elasticsearch",
  "App"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "server", "label": "Data Source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": {
     "query": "label_values(es_cluster_status,cluster)"
    }
   },
   {
    "name": "node",
    "label": "Node name",
    "query": {
     "query": "label_values(es_os_cpu_percent{cluster=\"$cluster\"},pod)"
    }
   },
   {
    "name": "interval",
    "label": "Interval",
    "query": "5m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "KPI", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Cluster Health",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(es_cluster_status{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Breakers Tripped",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(es_circuitbreaker_tripped_count{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "CPU Usage Avg.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (es_os_cpu_percent{cluster=\"$cluster\",node=~\"$node\"} ) / count (es_os_cpu_percent{cluster=\"$cluster\",node=~\"$node\"} )"
    }
   ]
  },
  {
   "title": "JVM Memory Used Avg.",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (es_os_mem_used_bytes{cluster=\"$cluster\",node=~\"$node\"}) / sum (es_os_mem_total_bytes{cluster=\"$cluster\",node=~\"$node\"}) * 100"
    }
   ]
  },
  {
   "title": "Nodes",
   "type": "stat",
   "description": "Number of nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(es_cluster_nodes_number{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Data Nodes",
   "type": "stat",
   "description": "Number of data nodes in the cluster",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(es_cluster_datanodes_number{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Pending Tasks",
   "type": "stat",
   "description": "Cluster level changes which have not yet been executed",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(es_cluster_pending_tasks_number{cluster=~\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Open File Descriptors Per Cluster",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (es_process_file_descriptors_open_number{cluster=\"$cluster\",node=~\"$node\"})"
    }
   ]
  },
  { "title": "Shards", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Active Primary Shards",
   "type": "stat",
   "description": "The number of primary shards in your cluster. This is an aggregate total across all indices.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 5 },
   "repeat": "shard_type",
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(es_cluster_shards_number{cluster=~\"$cluster\",type=\"active_primary\"})"
    }
   ]
  },
  {
   "title": "Active Shards",
   "type": "stat",
   "description": "Aggregate total of all shards across all indices, which includes replica shards",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(es_cluster_shards_number{cluster=\"$cluster\",type=\"active\"})"
    }
   ]
  },
  {
   "title": "Initializing Shards",
   "type": "stat",
   "description": "Count of shards that are being freshly created",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(es_cluster_shards_number{cluster=\"$cluster\",type=\"initializing\"})"
    }
   ]
  },
  {
   "title": "Relocating Shards",
   "type": "stat",
   "description": "The number of shards that are currently moving from one node to another node.",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(es_cluster_shards_number{cluster=\"$cluster\",type=\"relocating\"})"
    }
   ]
  },
  {
   "title": "Delayed Unassigned Shards",
   "type": "stat",
   "description": "Shards delayed to reduce reallocation overhead",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(es_cluster_shards_number{cluster=\"$cluster\",type=\"delayed_unassigned\"})"
    }
   ]
  },
  {
   "title": "Unassigned Shards",
   "type": "stat",
   "description": "The number of shards that exist in the cluster state, but cannot be found in the cluster itself",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(es_cluster_shards_number{cluster=\"$cluster\",type=\"unassigned\"})"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 } },
  {
   "title": "Documents indexed",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(es_indices_doc_number{cluster=~\"$cluster\"})",
     "legendFormat": "Documents"
    }
   ]
  },
  {
   "title": "Index Size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(es_indices_store_size_bytes{cluster=~\"$cluster\"})",
     "legendFormat": "Index Size"
    }
   ]
  },
  { "title": "Disk and Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Disk usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "percentunit", "label": "Disk Usage %" }
   ],
   "targets": [
    {
     "expr": "1-(es_fs_total_free_bytes{cluster=\"$cluster\",node=~\"$node\"}/es_fs_total_total_bytes{cluster=\"$cluster\",node=~\"$node\"})",
     "legendFormat": "{{node}}"
    }
   ]
  },
  {
   "title": "Network usage",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "Bps", "label": "Bytes/sec" }
   ],
   "targets": [
    {
     "expr": "irate(es_transport_tx_bytes_count{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: sent "
    },
    {
     "expr": "-irate(es_transport_rx_bytes_count{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
     "legendFormat": "{{node}}: received"
    }
   ]
  },
  {
   "title": "CPU and Memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load average",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 33 },
     "yaxes": [
      { "format": "short", "label": "CPU load" }
     ],
     "targets": [
      {
       "expr": "es_os_load_average_one_minute{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "load1: {{node}}"
      },
      {
       "expr": "es_os_load_average_five_minutes{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "load5: {{node}}"
      },
      {
       "expr": "es_os_load_average_fifteen_minutes{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "load15: {{node}}"
      }
     ]
    },
    {
     "title": "CPU usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 33 },
     "yaxes": [
      { "format": "percent", "label": "CPU usage" }
     ],
     "targets": [
      {
       "expr": "es_os_cpu_percent{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "JVM memory usage",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "es_jvm_mem_heap_used_bytes{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}} used: heap"
      },
      {
       "expr": "es_jvm_mem_heap_max_bytes{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}} max: heap"
      },
      {
       "expr": "es_jvm_mem_nonheap_used_bytes{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}} used: non-heap"
      },
      {
       "expr": "es_jvm_mem_nonheap_committed_bytes{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}} max: committed"
      },
      {
       "expr": "es_jvm_mem_pool_peak_used_bytes{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}} peak used pool: {{pool}}"
      }
     ]
    },
    {
     "title": "JVM memory committed",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 44 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "es_jvm_mem_heap_committed_bytes{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}} committed: heap"
      },
      {
       "expr": "es_jvm_mem_heap_max_bytes{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}} max: heap"
      },
      {
       "expr": "es_jvm_mem_nonheap_committed_bytes{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}} committed: non-heap"
      }
     ]
    }
   ]
  },
  {
   "title": "JVM Garbage Collection",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "GC count",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "short", "label": "GCs" }
     ],
     "targets": [
      {
       "expr": "irate(es_jvm_gc_collection_count{cluster=\"$cluster\",pod=~\"$node\"}[$interval])",
       "legendFormat": "{{pod}} - {{gc}}"
      }
     ]
    },
    {
     "title": "GC time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(es_jvm_gc_collection_time_seconds{cluster=\"$cluster\",pod=~\"$node\"}[$interval])",
       "legendFormat": "{{pod}} - {{gc}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Translog",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total translog operations",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(es_index_translog_operations_number{cluster=\"$cluster\",pod=~\"$node\"}[$interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Total translog size in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "irate(es_index_translog_size_bytes{cluster=\"$cluster\",pod=~\"$node\"}[$interval])",
       "legendFormat": "{{pod}} "
      }
     ]
    }
   ]
  },
  {
   "title": "Breakers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Tripped for breakers",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "es_circuitbreaker_tripped_count{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}}: {{name}}"
      }
     ]
    },
    {
     "title": "Estimated size in bytes of breaker",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "es_circuitbreaker_estimated_bytes{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}}: {{name}}"
      },
      {
       "expr": "es_circuitbreaker_limit_bytes{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}}: limit for {{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Documents",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Documents count on node",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "es_indices_merges_total_docs_count{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Documents indexed rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
     "yaxes": [
      { "format": "short", "label": "index calls/s" }
     ],
     "targets": [
      {
       "expr": "irate(es_indices_indexing_index_current_number{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Documents deleted rate",
     "type": "graph",
     "description": "Count of deleted documents on this node",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short", "label": "Documents/s" }
     ],
     "targets": [
      {
       "expr": "irate(es_index_indexing_delete_current_number{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Documents merged rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "short", "label": "Documents/s" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_merges_current_number{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Documents merged bytes",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "decbytes", "label": "Bytes/s" }
     ],
     "targets": [
      {
       "expr": "irate(es_indices_merges_current_size_bytes{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Times",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Query time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(es_indices_search_query_time_seconds{cluster=\"$cluster\",node=~\"$node\"}[$interval]) ",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Indexing time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(es_indices_indexing_throttle_time_seconds{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Merging time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(es_indices_merges_total_time_seconds{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Throttle time for index store",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 35 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(es_indices_merges_total_throttled_time_seconds{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Total Operations stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Operations  rate",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
     "yaxes": [
      { "format": "short", "label": "Operations/s" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_indexing_index_count{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}: indexing"
      },
      {
       "expr": "rate(es_indices_search_query_count{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}: query"
      },
      {
       "expr": "rate(es_indices_search_fetch_count{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}: fetch"
      },
      {
       "expr": "rate(elasticsearch_indices_merges_total{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}: merges"
      },
      {
       "expr": "rate(elasticsearch_indices_refresh_total{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}: refresh"
      },
      {
       "expr": "rate(elasticsearch_indices_flush_total{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}: flush"
      },
      {
       "expr": "rate(elasticsearch_indices_get_exists_total{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}: get_exists"
      },
      {
       "expr": "rate(elasticsearch_indices_get_missing_total{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}: get_missing"
      },
      {
       "expr": "rate(elasticsearch_indices_get_tota{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}: get"
      },
      {
       "expr": "rate(elasticsearch_indices_indexing_delete_total{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}: indexing_delete"
      }
     ]
    },
    {
     "title": "Total Operations time",
     "type": "graph",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "s", "label": "Time" }
     ],
     "targets": [
      {
       "expr": "irate(es_indices_indexing_delete_time_seconds{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}: indexing"
      },
      {
       "expr": "irate(es_indices_search_query_time_seconds{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}: query"
      },
      {
       "expr": "irate(es_indices_search_fetch_time_seconds{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}: fetch"
      },
      {
       "expr": "irate(elasticsearch_indices_merges_total_time_seconds_total{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}: merges"
      },
      {
       "expr": "irate(elasticsearch_indices_refresh_time_seconds_total{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}: refresh"
      },
      {
       "expr": "irate(elasticsearch_indices_flush_time_seconds{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}: flush"
      },
      {
       "expr": "irate(elasticsearch_indices_get_exists_time_seconds{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}: get_exists"
      },
      {
       "expr": "irate(elasticsearch_indices_get_time_seconds{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}: get_time"
      },
      {
       "expr": "irate(elasticsearch_indices_get_missing_time_seconds{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}: get_missing"
      },
      {
       "expr": "irate(elasticsearch_indices_indexing_delete_time_seconds_total{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}: indexing_delete"
      },
      {
       "expr": "irate(elasticsearch_indices_get_time_seconds{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{name}}: get"
      }
     ]
    }
   ]
  },
  {
   "title": "Thread Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thread Pool operations rejected",
     "type": "graph",
     "gridPos": { "h": 20, "w": 6, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(es_threadpool_threads_count{cluster=\"$cluster\",node=~\"$node\", type=\"rejected\"}[$interval])",
       "legendFormat": "{{node}}: {{ type }}"
      }
     ]
    },
    {
     "title": "Thread Pool operations queued",
     "type": "graph",
     "gridPos": { "h": 20, "w": 6, "x": 6, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(es_threadpool_tasks_number{cluster=\"$cluster\",node=~\"$node\", type=\"queue\"}[$interval])",
       "legendFormat": "{{node}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Thread Pool threads active",
     "type": "graph",
     "gridPos": { "h": 20, "w": 6, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "es_threadpool_threads_number{cluster=\"$cluster\",node=~\"$node\",type=\"active\"}",
       "legendFormat": "{{node}}: {{ name }}"
      }
     ]
    },
    {
     "title": "Thread Pool operations completed",
     "type": "graph",
     "gridPos": { "h": 20, "w": 6, "x": 18, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(es_threadpool_threads_count{cluster=\"$cluster\",node=~\"$node\", type=\"completed\"}[$interval])",
       "legendFormat": "{{node}}: {{ name }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Caches",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Field data memory size",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "bytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "es_indices_fielddata_memory_size_bytes{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Field data evictions",
     "type": "graph",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 27 },
     "yaxes": [
      { "format": "short", "label": "Evictions/s" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_fielddata_evictions_count{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Query cache size",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "bytes", "label": "Size" }
     ],
     "targets": [
      {
       "expr": "es_indices_querycache_cache_size_bytes{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Query cache evictions",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 8, "y": 38 },
     "yaxes": [
      { "format": "short", "label": "Evictions/s" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_querycache_evictions_count{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Evictions from filter cache",
     "type": "graph",
     "gridPos": { "h": 11, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "short", "label": "Evictions/s" }
     ],
     "targets": [
      {
       "expr": "rate(es_indices_requestcache_evictions_count{cluster=\"$cluster\",node=~\"$node\"}[$interval])",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Segments",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of index segments",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "es_indices_segments_number{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    },
    {
     "title": "Current memory size of segments in bytes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 35 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "es_indices_segments_memory_bytes{cluster=\"$cluster\",node=~\"$node\"}",
       "legendFormat": "{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Indices: Count of documents and Total size",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of documents with only primary shards",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "es_index_doc_number{context=\"primaries\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Total size of stored index data in bytes with only primary shards on all nodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 36 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "es_index_merges_total_size_bytes{context=\"primaries\"}",
       "legendFormat": "{{index}}"
      }
     ]
    },
    {
     "title": "Total size of stored index data in bytes with all shards on all nodes",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "es_index_store_size_bytes{cluster=~\"$cluster\"}",
       "legendFormat": "{{index}}"
      }
     ]
    }
   ]
  }
 ]
}